name: Build and Publish Bundles

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install dependencies
        run: npm ci

      - name: Build CommonJS bundle
        run: npm run build:bundle

      - name: Build ES Module bundle
        run: npm run build:module:bundle

      - name: Stage bundle artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          find dist -type f \( -name '*.mjs' -o -name '*.cjs' -o -name 'flexsearch.bundle*.js' -o -name 'node.js' \) -print0 | xargs -0 --no-run-if-empty git add

      - name: Commit and push
        run: |
          if git diff --cached --quiet; then
            echo "No bundle updates to commit"
            exit 0
          fi

          BRANCH="${GITHUB_REF#refs/heads/}"
          if [ -z "$BRANCH" ]; then
            echo "Unsupported ref: $GITHUB_REF"
            exit 0
          fi

          git commit -m "chore: update dist bundles [skip ci]"
          git push origin "HEAD:$BRANCH"
