name: Build and Publish Bundles

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-publish:
    if: github.actor != 'github-actions[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: source

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: source/package-lock.json

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Install dependencies
        run: npm install
        working-directory: source

      - name: Build CommonJS bundle
        run: npm run build:bundle
        working-directory: source

      - name: Build ES Module bundle
        run: npm run build:module:bundle
        working-directory: source

      - name: Checkout release repository
        uses: actions/checkout@v4
        with:
          repository: AssistOS-AI/flexsearch-releases
          token: ${{ secrets.FLEXSEARCH_RELEASES_TOKEN }}
          fetch-depth: 0
          path: release
          ref: main

      - name: Sync bundles into release repo
        run: |
          mkdir -p dist
          rsync -a --delete ../source/dist/ dist/
        working-directory: release

      - name: Commit and push bundles
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist
          if git diff --cached --quiet; then
            echo "No bundle updates to commit"
            exit 0
          fi
          git commit -m "chore: update dist bundles [skip ci]"
          git push origin HEAD:main
        working-directory: release
